# Generated by Django 4.1.3 on 2022-12-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('Technology', models.CharField(default='html', max_length=30)),
                ('description', models.TextField(default='DataFlair Django tutorials')),
            ],
        ),
    ]
