# Generated by Django 4.1.3 on 2022-12-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='Technology',
            new_name='technology',
        ),
    ]
